export class Language {

    ClAdmin: string;
    profile: string;
    settings: string;
    home: string;
    dashboard: string;
    Customers: string;
    allcustomers: string;
    ServiceProviders: string;
    allservices: string;
    Drivers: string;
    alldrivers: string;
    Bookings: string;
    pastbookings: string;
    allbookings: string;
    onbookings: string;
    addService: string;
    editserviceprovider: string;
    //for loginpage
    signInText: string;
    email: string;
    password: string;
    loginBtn: string;
    //for Driver
    driverName: string;
    driverEmail: string;
    createNewDriver: string;
    addDriver: string;
    firstName: string;
    lastName: string;
    MCNumber: string;
    // for dashboard
    bookingCount: string;
    customerCount: string;
    driverCount: string;
    serviceProviderCount: string;
    todaysBookingRequests: string;
    todaysRevenue: string;
    totalRevenue: string;
    //for customer component
    customerName: string;
    customerEmail: string;
    action: string;
    details: string;
    createCustomer: string;
    //delete customer
    deleteCustomer: string;
    deleteButton: string;
    cancelButton: string;
    customerDeleteText: string;
    //edit customer
    createCustomerName: string;
    createCustomerLastName: string;
    createCustomerUserName: string;
    createCustomerEmail: string;
    addCustomer: string;
    customerCountryCode: string;
    customerPhone: string;
    companyName: string;
    companyAddress: string;
    customerSignUp: string;
    customerClose: string;
    // block option
    blockCustomerTitle: string;
    unblockButton: string;
    blockButton: string;
    customerUnblockText: string;
    customerBlockText: string;
    // id details
    customerDetails: string;
    addServiceProvider: string;
    serialNumber: string;
    allServiceProvider: string;
    customerPassword: string;
    customerRepeatPassword: string;
    latitude: string;
    longitude: string;
    // booking
    bookingId: string;
    pickUpName: string;
    pickUpPhoneNo: string;
    pickUpAddress: string;
    deliveryName: string;
    deliveryPhoneNo: string;
    deliveryAddress: string;
    price: string;
    bookingStatus: string;
    cancelBooking: string;
    bookingdetails: string;
    cancelBookingTitle: string;
    cancelBookingText: string;
    cancelBookingBtn: string;
    serviceproviderblockText: string;
    serviceproviderUnblockText: string;
    serviceProvider: string;
    deleteserviceprovider: string;
    serviceproviderDeleteText: string;
    keyMessage: string;
    role: string;
    adminVerified: string;
    isDeleted: string;
    isBlocked: string;
    emailRequired: string;
    invalidEmail: string;
    adminOption: string;
    customerOption: string;
    appVersion: string;
}